### ISSUE TITLE
Error while start all.

### ISSUE THREAD

**Issue by Somebi** [sinterlkaas/YetAnotherRelogger#4]
Getting error inside YAR after pressing start all:

[08.12.2012 19:39:11]    at YetAnotherRelogger.Helpers.Bot.DiabloClass.Start()
   at YetAnotherRelogger.Relogger.StartBoth(BotClass bot)
   at YetAnotherRelogger.Relogger.ReloggerWorker()

Maybe there is some conflict with .NET versions? What version of .NET sdk are you using?

And i'm not getting message "Windows protected your PC" when opening my compiled version for the first time.
Probably i'm doing something wrong...
There were problems with security options and mt.exe location.

I had to edit postcompile command to:

"$(ProgramFiles)\Windows Kits\8.0\bin\x86\mt.exe" -manifest "$(ProjectDir)Properties\app.manifest"  -outputresource:"$(TargetDir)$(TargetFileName)"
if “$(ConfigurationName)”==”Release” "$(ProjectDir)..\ThirdParty\PETool\PETool.exe" "$(TargetDir)$(TargetFileName)" /DeStamp /VerChange "OriginalFilename" "" /VerChange "InternalName" "" /VerChange "FileVersion" "" /VerChange "ProductVersion" "" /VerChange "Assembly Version" ""

You are using sdk 7.0A? Couldn't find that version of sdk.

**Comment by Somebi** [comment]
The problem was with new feature related to D3perf file. It it's not been provided, then it throws that error.
I have selected D3perf file location for all bots and now it drops and error:

[08.12.2012 20:57:54] <mymail> Failed to copy D3Prefs file: System.IO.IOException: The process cannot access the file 'C:\Users\myuser\Documents\Diablo III\D3Prefs.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at YetAnotherRelogger.Helpers.Bot.DiabloClass.D3Prefs()

**Comment by Somebi** [comment]
But all bots are working. Just need to wrap some code in try&catch somewhere there. I have tired. Hope you'll find that faster in your code. ;) Thanks for the great tool.

**Comment by sinterlkaas** [comment]
Yes I am aware on the issue with MT and pathing.. did not find a easy way to fix this (mayb I should just add the mt.exe to thirdparty folder like PETool.exe)

**Comment by Somebi** [comment]
Yes that's good idea. Relative path will avoid fixing mt.exe path manually.

**Comment by sinterlkaas** [comment]
Fixed in latest Experimental build :)
